contact_links:
  - name: Help or Questions 🙀
    url: https://spectrum.chat/zeit-ui/general?tab=posts
    about: This issue tracker is not for support questions. Please refer to the Spectrum's community.
